# -*- coding: utf-8 -*-
"""
TencentBlueKing is pleased to support the open source community by making 蓝鲸智云-抽奖系统(BlueKing-BK-LOTTERY) available.
Copyright (C) 2017-2023 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at https://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
"""
# Generated by Django 3.2.4 on 2022-12-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_appmetaconfig_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='appmetaconfig',
            name='conf_type',
            field=models.CharField(
                default='0',
                max_length=10,
                verbose_name='配置项分类'),
        ),
        migrations.AddField(
            model_name='appmetaconfig',
            name='name',
            field=models.CharField(
                default='',
                max_length=100,
                verbose_name='配置中文名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appmetaconfig',
            name='remark',
            field=models.TextField(
                verbose_name='备注'),
        ),
    ]
